site_name: BaselFirewall
site_description: A Python-based personal firewall for Linux with advanced security features
theme:
  name: material
  palette:
    primary: indigo
    accent: deep purple
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Installation: INSTALL.md
  - API Reference: API.md
  - Security: SECURITY.md
  - Contributing: CONTRIBUTING.md
  - FAQ: FAQ.md
  - Performance: PERFORMANCE.md
  - Changelog: CHANGELOG.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search 